from environment.env_configuration import prepare_environment
from feature_engineering.feature_engineering_commands import execute_feature_engineering

prepare_environment()
execute_feature_engineering()